name: spiderweb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  bloc: 
  flutter_bloc: 
  equatable: 
  mssql_connection: ^1.1.3
  flutter_easyloading:
  intl:

  # mysql_client: ^0.0.27
  # mysql1: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
